onboarding = false

[theme]
name = "catppuccin"

[ui]
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[terminal]
default_shell = "/opt/homebrew/bin/fish"

[experimental]
pane_history = false
