local map = require("config.keymaps.mapFn")
map("i", "æ", function()
  return vim.fn["codeium#Accept"]()
end, { desc = "codeium accept" })
map("i", "…", function()
  return vim.fn["codeium#CycleCompletions"](1)
end, { desc = "codeium cycle" })

map("i", "Ú", function()
  return vim.fn["codeium#CycleCompletions"](-1)
end, { desc = "codeium cycle backward" })

map("i", "Æ", function()
  return vim.fn["codeium#Clear"]()
end, { desc = "codeium clear" })
