theme = "base16_transparent_custom"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
true-color = true
completion-trigger-len = 1
scrolloff = 8
shell = ["fish", "-c"]
cursorline = true


[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "󰩐 NORMAL"
mode.insert = "󰲶 INSERT"
mode.select = "󰝱 SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = true
ignore = false
git-ignore = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"=" = { "=" = ":format" }
"space" = { x = ":buffer-close", "." = "code_action", e = ":sh wezterm-open-yazi-left" } # buffer close
"X" = "extend_line_above"
"D" = "kill_to_line_end"
"L" = ":buffer-next"
"H" = ":buffer-previous"
"C-x" = ":buffer-close"
# g = [":new", "insert-output yazi", ":buffer-close!", ":redraw"]
# [keys.insert]
# "space" = { "." = "completion"}
