[tools]

node = "lts"
# "npm:typescript" = "latest"
# "npm:corepack" = "latest"
gleam = "latest"
elixir = "latest"
erlang = "latest"
rebar = "latest"  # rebar must install erlang # "npm:biome" = "latest";
deno = "latest"
go = "latest"
bun = "1"
uv = "latest"
python = "3"
# "npm:pnpm" = "latest"
# pnpm = "latest"
# python = ["3.10" "3.11"];

[settings]
# disable warning but I don't know what it is
idiomatic_version_file_enable_tools = ["python"]
# when open project need python uv auto load venv
python.uv_venv_auto = true
# python.uv_venv_auto need experimental=rue
experimental = true

#          ┌──────────────────────────────────────────────────────────┐
#                              if not use uv_env_at
#           you need to add this into mise.toml in the project itself
# 
# [env]
# _.python.venv = { path = ".venv", create = true }
#          └──────────────────────────────────────────────────────────┘
